title: TPASystem Wiki
description: Documentación oficial del addon TPASystem para Minecraft Bedrock
theme: just-the-docs
color_scheme: dark

url: "https://tuusuario.github.io/TPASystem"
aux_links:
  "Ver en GitHub":
    - "//github.com/tuusuario/TPASystem"
